// q8_0 KV cache direct-loading instances (V100 fork), not generated by generate_cu_files.py

#include "../fattn-mma-f16.cuh"

DECL_FATTN_MMA_F16_CASE_Q8_0(256, 256, 16, 2);
DECL_FATTN_MMA_F16_CASE_Q8_0(256, 256, 32, 2);
DECL_FATTN_MMA_F16_CASE_Q8_0(256, 256, 32, 1);
DECL_FATTN_MMA_F16_CASE_Q8_0(256, 256, 64, 1);
